### ISSUE TITLE
newb

### ISSUE THREAD

**Issue by rkross888** [SuperrSonic/WiiMC-SSLC#1]
I am have problems compiling so I can See NTFS 8T Drive, love your tweaks, big improvement. Can I have another way to contact you.
thank you ryan

**Comment by SuperrSonic** [comment]
Thanks.

Considering your goal, you should be compiling the official version. I can help depending on your issue, it was a big headache when I did it, and even when it compiled, the dol was freezing on ssa subtitles. I had to track down the right versions of the portlibs.

**Comment by rkross888** [comment]
Thank you for reply'n,
lol, i so understand, I have been looking over you changes and the official version to understand what is going on for about 2 weeks, and I believe I am starting to get some of it. Not that i could write any myself mind you,but I am starting to understand how to is formed.

It did take a while before I could find that devkitpro v25 is the only version not shotting me errors and can compile it., I kinda cheated,,Cause I used your pak of Portlibs. 

I was using MELD commenting out EXT2 in the fileop.ccp but then I would get double drives (ex. 2 sd, 2 HD)  I was able to stop this by not commenting out but instead add return; after CASE_EXT which i believe stops the rest of ext2 code from exe.

-I was not able to add in Audio Normalizer option you had,,told me not in scope.(?)
-I Also had Problems pause to home page via home key during video after adding your video settings of 720 in,,wii would crash
-I also get 'WIIMC does not have DVD access - AHBPROT is not enabled. maybe this is a port i need.

+ On the wish list would be mplayer option to watch video at 1.5 speed faster.

finally I had to return the 8T drive before I can not,,but I need more HD space and this has to be working first.so...

Thanks again..,
ryan

**Comment by SuperrSonic** [comment]
-I need more info, if you straight up merged that commit, I have no idea why it would fail.
-Assuming you're talking about 720 width, this does not have any effect unless you use arguments.
-Does this not happen on the official version? It just means hardware protection is enabled and access to the DVD commands is unavailable.

**Comment by rkross888** [comment]
-I would use meld (visual diff and merge tool) to view your modded ver. and the offical version copy in a     3 folder, and it allows me to copy just the diff of 2 file, ie. your commented out ext2 code.
-Yes 720 width.IDK why but the compiled code would freeze the wii, when going to supend during a video via home key. P.S. your pre-compiled dol works fine, minus width are cut,,such as text.
 -The Offical Version does see a DVD & a data dvd,,mine and yours does not.

**Comment by SuperrSonic** [comment]
And you checked with 33278ece42e25a0b7a71cf6ca4d1a6b78bdb75e5 to make sure you didn't miss anything?
Are you certain you're loading the dol with <ahb_access/>? I imagine you are if you tried the 720 mode.

**Comment by rkross888** [comment]
Thank you,
I looked at the link you gave,,and the audio norm (i think ) is working, ( at least no compiling errors) 
Sorry IDK what you mean load the dol with  "<ahb_access/>? "

**Comment by SuperrSonic** [comment]
If you have IOS58 detected with HBC, you can add that ahb_access to the meta.xml, to enable DVD playback in WiiMC. Audio norm should only work if you manually edit the settings xml.

**Comment by rkross888** [comment]
-Right again,,Looking at the Official Version I seen they have <no_iso_reload/> in the meta.xml,,And this fixed my DVD issue.
-settings.cpp 
	createXMLSetting("videoFull", "Videos in Fullscreen", toStr(WiiSettings.videoFull));
	createXMLSetting("audioNorm", "Volume Normalizer", toStr(WiiSettings.audioNorm));
-menu.cpp
	sprintf(options.name[i++], "Videos in Fullscreen");
	sprintf(options.name[i++], "Volume Normalizer");
&
			case 12:
				WiiSettings.videoFull ^= 1;
				break;
			case 13:
				WiiSettings.audioNorm ^= 1;
				break;
&
			sprintf (options.value[12], "%s", WiiSettings.videoFull ? "On" : "Off");
			sprintf (options.value[13], "%s", WiiSettings.audioNorm ? "1" : "2");
but I can't tell if it should be  ? "On" : "Off"); for audioNorm
I think it is working.
Any ideas on playing video 1.5x faster?

**Comment by SuperrSonic** [comment]
An easy way to know if audio norm stuff is working is to go to mplayer.c and change the value 1:0.25 or 2:0.25 to be really high, like 0.95 and you should be able to tell straight away.

For speed try m_config_set_option(mconfig,"speed","1.5");

Skimming through the manual it's even possible to change tempo with an audio filter.
http://www.mplayerhq.hu/DOCS/man/en/mplayer.1.html

**Comment by rkross888** [comment]
Thank you,,I am tryiing now
-Is there not a way to instead passing "1.5" into mplayer.c,,but make it a string so i change select speed in the menu..same question for Audio Norm.?

**Comment by rkross888** [comment]
It Works,,Yea,,now i am just trying to also pass -af scaletempo in the same line, to get away from chipmunk sounds

Thank you again..
ps stll have to try it out on >3T drive

**Comment by SuperrSonic** [comment]
Cool, I don't think I can help with making speed or other stuff easily changeable from the settings menu, it's something I tried doing at first but it was too complicated for something I'd never use.

I know MPlayer CE has a way to change speed on the spot, so you might want to check that as well.

**Comment by rkross888** [comment]
Also, I can get it to work,,Norm and Speed,,but i wont turn off,,untill I boot into the offical version and back???

**Comment by rkross888** [comment]
i try'd this
void wiiSetVidSpeed()
{
	m_config_set_option(mconfig,"af","scaletempo") && (mconfig,"speed","1.5");
}
no go,
Would you know where I can find the source for Mplayer CE,,all i found was the precompile ones,

**Comment by SuperrSonic** [comment]
https://github.com/ExtremsCorner/mplayer-ce is the one I use for reference, no idea what the last change is on the main version.

**Comment by rkross888** [comment]
do you how to combin these 2 commmands?
m_config_set_option(mconfig,"af","scaletempo");
m_config_set_option(mconfig,"speed","1.5");

I have try && (()) and +,,,i need the command to go to mplayer as -af scaletempo -speed 1.5

**Comment by SuperrSonic** [comment]
Is it necessary? I would use both just as you wrote them above.

Is m_config_set_option(mconfig,"af","scaletempo","speed","1.5"); not valid?

**Comment by rkross888** [comment]
yea not valid,,,Wont not compile mplayer

**Comment by rkross888** [comment]
I give up. I can't get it to work,,Mplayer ce does it,,,idk why wiimc can't. just freezes and crashes..
thank you for you help.
