### ISSUE TITLE
YouTube Support

### ISSUE THREAD

**Issue by larsenv** [SuperrSonic/WiiMC-SSLC#10]
Mirror of what I said on the GBAtemp thread:

@SuperrSonic Could you possibly add YouTube support to your WiiMC mod? TubeFixer is a project to use YouTube on WiiMC, but it needs you to make an API key.

However, if you use the latest TLS, which can be done if you compile wolfSSL for the Wii, you won't have to proxy video feeds, but you still need an API key.

**Comment by viktormax3** [comment]
Try use this commit to inspire a wolfssl port to wiimc
https://github.com/cyan06/usbloadergx/pull/1/commits/f346e8280d4cb1e4efba3984682b133ead8528bb
