### ISSUE TITLE
Fonts not loading

### ISSUE THREAD

**Issue by NasrinAtiyeh** [SuperrSonic/WiiMC-SSLC#12]
Okay, so I've been trying to figure this out for 3 hours now. I've tried putting subfont.tff and monospace.tff in the main directory (apps/wiimc), tried making a fonts folder, and even scrubbed through several files of the code to maybe get a hint of where I should put them, but nothing works.

What exactly am I doing wrong?

**Comment by SuperrSonic** [comment]
It's apps/wiimc/subfont.ttf and enable visibility in the settings.

In a desperate effort to get memory usage down I removed a lot of language related code, libfribidi is no longer supported, for example. So, if you try loading certain subtitles it won't work.

Monospace is not currently working as intended, it only works on MKV files with a subtitle mime type. It's just an awkward workaround to load another font.

**Comment by NasrinAtiyeh** [comment]
Yes, I've tried that, and it still does not load.

**Comment by SuperrSonic** [comment]
Does it work on official WiiMC?

**Comment by NasrinAtiyeh** [comment]
Yes. When I use your modification, the subtitle font doesn't get recognized.

**Comment by SuperrSonic** [comment]
In the settings, try turning 'Monospaced' off.

**Comment by NasrinAtiyeh** [comment]
Monospace is turned off by default, so it's not that.

**Comment by SuperrSonic** [comment]
I know, but I can't predict what settings you've changed. This is as much as I can do without a sample.
Unless... your font is like 5 MB big.

**Comment by NasrinAtiyeh** [comment]
I'm using Arial and Arial MT.

**Comment by SuperrSonic** [comment]
Are you still available for testing? I have some changes related to subtitles, but I'd like to have this solved before I release an update.

**Comment by SuperrSonic** [comment]
Can't reproduce.
