### ISSUE TITLE
missing brstm.o - can't compile

### ISSUE THREAD

**Issue by Fledge68** [SuperrSonic/WiiMC-SSLC#16]
i'm using ppc r26 and libogc 1.8.12

when i compile brstm.o is never made and my compile fails.

do i need a different libogc? or a special lib?

**Comment by SuperrSonic** [comment]
Latest devkitppc will most definitely fail, it's best to stick with r24, not sure about libogc as the build I use doesn't have any identification besides being from 2011.

Can you check to see if there's an actual error message while building brstm.o? Can you build regular WiiMC?

**Comment by Fledge68** [comment]
Hey thanks for the reply!
yes i can compile regular wiimc. i figured out that he used ppc r25 (originally r24 but one of the last commits he upped to r25) and libogc 1.8.12

yours uses ppc r26 because i see a commit where you raised gcc to 4.6.3 which was released as ppc r26. plus libogc 1.8.12 is still the same because 1.8.14 requires and extra arg and fails.

the problem is you backported some code that allows to play brstm files. this causes my compile to fail. i was wondering if i needed to do some special ./config command before i call make?

or maybe you could give me a little tutorial on how you compile wiimc-slc?

**Comment by SuperrSonic** [comment]
Can you tell me which commit? I don't remember doing anything related to that for the brstm stuff.

As for building, if you've got regular WiiMC working then you've got this.
Nothing else is needed, in fact you can build it with less, because I dropped some things (like fribidi)

**Comment by Fledge68** [comment]
this commit - https://github.com/SuperrSonic/WiiMC-SSLC/commit/6db8e294951b87bd367734bc339178ab0aceeb2b

i think its the stuff in ffmpeg/libavformat that doesnt work for me.  for some reason even though you added 
OBJS-$(CONFIG_BRSTM_DEMUXER)             += brstm.o
to the makefile it still doesn't make that file for me.

I'm on windows using msys2 to compile.

**Comment by SuperrSonic** [comment]
I wanted to know why you think I changed to r26.

I'm at a loss for what it could be, you could try removing the brstm references and see if it builds then.
