### ISSUE TITLE
Actually about WiiXplorer-SS

### ISSUE THREAD

**Issue by TheAlienDrew** [SuperrSonic/WiiMC-SSLC#18]
What ever happened to the source code for `WiiXplorer-SS`? It seems the repo (assumably at https://github.com/SuperrSonic/WiiExplorer-SS) has long since been down?

**Comment by SuperrSonic** [comment]
I took it down because people started using it under the impression that it offered something new, while it only had tiny visual changes.

I hoped to release something worthwhile eventually but I've since lost interest.

**Comment by TheAlienDrew** [comment]
> I took it down because people started using it under the impression that it offered something new, while it only had tiny visual changes.
> 
> I hoped to release something worthwhile eventually but I've since lost interest.

Even if little changes, I think it would still be worth while to keep the source code up, so others can fork and do as they wish with it.
