### ISSUE TITLE
576i doesn't look right

### ISSUE THREAD

**Issue by HeteroChromia420** [SuperrSonic/WiiMC-SSLC#19]
Hello, while trying out WiiMC-SS, i've noticed that 576i (PAL 50hz) doesn't look right on this app, with the lower part of the screen being black, and the app not using all of the screen. would it be possible to have this issue looked into and solved?

**Comment by SuperrSonic** [comment]
This should be fixed, but I haven't had time to sort some things out. I lost most of the building environment and new builds are now bigger than they were before so I'm not sure whether to release an update or get a few more changes in.

**Comment by HeteroChromia420** [comment]
i'd argue that updates to a program should come as they're ready, specially if they include bug fixes, but that's my two cents about it.
