### ISSUE TITLE
Korean support

### ISSUE THREAD

**Issue by DDinghoya** [SuperrSonic/WiiMC-SSLC#2]
I have completed the translation of ko.lang as below link;

https://github.com/DDinghoya/WiiMC-SSLC/blob/master/source/lang/ko.lang

Would you please apply to it?

Best regards.

**Comment by SuperrSonic** [comment]
Awesome, I've now added it.

I've removed the function to download fonts, so the user must manually dl and place a "ko.ttf" on their WiiMC folder. It will still default to English.

I tested using the one from the official WiiMC, which I've now added here as well: https://github.com/SuperrSonic/WiiMC-SSLC/blob/master/fonts/ko.ttf

**Comment by DDinghoya** [comment]
Thank you for your strong support!!! :)
