### ISSUE TITLE
Add compilation instructions in readme?

### ISSUE THREAD

**Issue by HeteroChromia420** [SuperrSonic/WiiMC-SSLC#21]
Title. I'm interested in running the latest github version of WiiMC-SSLC on my wii, can compilation instructions be added to the readme file?

**Comment by SuperrSonic** [comment]
Since instructions are still available on the WiiMC site, I don't see much use for this. I haven't messed much with the build process, but the makefile does have a few configs that can be enabled, just for compiling with NTFS and EXT2/3/4 libs.

**Comment by HeteroChromia420** [comment]
They don't seem to work for linux systems, either that or i'm missing a step. regardless of what i do it keeps complaining about a missing ft2build.h
