### ISSUE TITLE
Automated Builds / New Stable Release?

### ISSUE THREAD

**Issue by HeteroChromia420** [SuperrSonic/WiiMC-SSLC#22]
I think it would be neat if it would be possible to either have automated builds or a new stable release for those who are unable to get the app compiled (or dunno how to), could it be possible to have such a thing?

**Comment by SuperrSonic** [comment]
I don't have the resources to host a build system. For WiiMC I can't afford to put too much effort anyway. After the harddrive crash, I shared all my changes in a rather painful commit https://github.com/SuperrSonic/WiiMC-SSLC/commit/c1f994e718de051efa1e6fa1b091bbf90a695759

There's broken, unfinished stuff. Once I sort through it all, I will release an update, bump the version number and will probably put the project on hiatus until something interesting comes up.
