### ISSUE TITLE
Please Wait! Initializing Network

### ISSUE THREAD

**Issue by Badb0is** [SuperrSonic/WiiMC-SSLC#23]
Hello, First off, I love this application and the work done on this app. Its an amazing media player for 480p content. Lags a little on bigger files but works really well. I love being able to use the GC controller solely to use the app.

The only thing preventing this ability is the fact that the app launches the networking utility immediately after startup. I only have my wii connected to the internet sometimes. When the internet is not connected, the app hangs and the user is unable to cancel out of the network connection attempt with a GC controller. Which then makes the app unusable.

The only workaround I have is to make a wifi hotspot with the same credentials, which tricks the wii to connecting and lets u bypass the network dialogue.

Would love a fix here to make the app completely GCC compatible. Thanks!

**Comment by SuperrSonic** [comment]
Feel free to re-open if this issue is still present in the recent release.

**Comment by privacy313** [comment]
this seems to be present on the latest release
