### ISSUE TITLE
Support Kor/Eng conversion on keyboard

### ISSUE THREAD

**Issue by DDinghoya** [SuperrSonic/WiiMC-SSLC#3]
Is it possible to support Kor/Eng conversion(switch) on keyboard as below source?

WiiMC-SSLC/source/libwiigui/gui_keyboard.cpp

** Eng <-> Kor **

{
		{'q','Q'} <-> {'ㅂ','ㅃ'},
		{'w','W'} <-> {'ㅈ','ㅉ'},
		{'e','E'} <-> {'ㄷ','ㄸ'},
		{'r','R'} <-> {'ㄱ','ㄲ'},
		{'t','T'} <-> {'ㅅ','ㅆ'},
		{'y','Y'} <-> {'ㅛ','ㅛ'},
		{'u','U'} <-> {'ㅕ','ㅕ'},
		{'i','I'} <-> {'ㅑ','ㅑ'},
		{'o','O'} <-> {'ㅐ','ㅒ'},
		{'p','P'} <-> {'ㅔ','ㅖ'},
	},
	{
		{'a','A'} <-> {'ㅁ','ㅁ'},
		{'s','S'} <-> {'ㄴ','ㄴ'},
		{'d','D'} <-> {'ㅇ','ㅇ'},
		{'f','F'} <-> {'ㄹ','ㄹ'},
		{'g','G'} <-> {'ㅎ','ㅎ'},
		{'h','H'} <-> {'ㅗ','ㅗ'},
		{'j','J'} <-> {'ㅓ','ㅓ'},
		{'k','K'} <-> {'ㅏ','ㅏ'},
		{'l','L'} <-> ('ㅣ','ㅣ'},
		{';',':'},
		{'\'','"'}
	},
	{
		{'z','Z'} <-> {'ㅋ','ㅋ'},
		{'x','X'} <-> {'ㅌ','ㅌ'},
		{'c','C'} <-> {'ㅊ','ㅊ'},
		{'v','V'} <-> {'ㅍ','ㅍ'},
		{'b','B'} <-> {'ㅠ','ㅠ'},
		{'n','N'} <-> {'ㅜ','ㅜ'},
		{'m','M'} <-> {'ㅡ','ㅡ'},
		{',','<'},
		{'.','>'},
		{'/','?'},
		{'\0','\0'}
	}

**Comment by SuperrSonic** [comment]
Unfortunately I don't think I can do this. As a final resort I tried compiling a special build for you with the changes but the compiler gave a lot of warnings and the characters didn't display so I gave up.

**Comment by DDinghoya** [comment]
Thank you for your attempt at the issue I proposed.
