### ISSUE TITLE
Compile Error for ft2build.h

### ISSUE THREAD

**Issue by RedFireMRT84** [SuperrSonic/WiiMC-SSLC#33]
cd source/mplayer; make -f Makefile; cd ../..
make[1]: Entering directory '/wiimc-master/wiimc-master/source/mplayer'
/opt/devkitpro/devkitPPC/bin/powerpc-eabi-gcc -MD -MP -O3 -mcpu=750 -meabi -mrvl -msdata -mpaired -mmultiple -mstring -pipe -g -ffast-math -frename-registers -Wundef -Wall -Wno-switch -Wno-parentheses -Wpointer-arith -Wredundant-decls -Wmissing-prototypes -Wdisabled-optimization -Wno-pointer-sign -Wdeclaration-after-statement -std=gnu99  -O3 -mcpu=750 -meabi -mrvl -msdata -mpaired -mmultiple -mstring -pipe -g -ffast-math -frename-registers -DGEKKO -DHW_RVL -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE64_SOURCE -Ilibdvdread4 -I/opt/devkitpro/portlibs/ppc/include -I/opt/devkitpro/libogc/include -Ilibdvdread4 -Ilibdvdnav -I/opt/devkitpro/portlibs/ppc/include/freetype2 -I/opt/devkitpro/libogc/include/ogc/machine -I/opt/devkitpro/devkitPPC/../buildscripts/powerpc-eabi/gcc/gcc/include -I. -Iffmpeg  -DFF_API_MAX_STREAMS=0 -c -o command.o command.c
powerpc-eabi-gcc.exe: warning: switch '-mstring' is no longer supported
powerpc-eabi-gcc.exe: warning: switch '-mstring' is no longer supported
powerpc-eabi-gcc.exe: error: unrecognized command-line option '-mpaired'
powerpc-eabi-gcc.exe: error: unrecognized command-line option '-mpaired'
make[1]: *** [Makefile:789: command.o] Error 1
make[1]: Leaving directory 'wiimc-master/wiimc-master/source/mplayer'
filebrowser.cpp
In file included from wiimc-master/wiimc-master/source/wiimc.h:11,
                 from wiimc-master/wiimc-master/source/filebrowser.cpp:21:
wiimc-master/wiimc-master/source/utils/FreeTypeGX.h:27:10: fatal error: ft2build.h: No such file or directory
   27 | #include <ft2build.h>
      |          ^~~~~~~~~~~~
compilation terminated.
make[1]: *** [/opt/devkitpro/devkitPPC/base_rules:13: filebrowser.o] Error 1
make: *** [Makefile:111: build] Error 2

**Comment by RedFireMRT84** [comment]
How do I install that ft2build for libfreetype?

**Comment by SuperrSonic** [comment]
Hi, I setup the build environment back in 2015, I have no idea what your issue could be and I can't afford to spend time on something like this. I'm sure there's someone out there more than willing to help assist you in your search but I am not that person. Maybe a few years back.

I only accept issues specifically related to this fork, not generic WiiMC problems.
