### ISSUE TITLE
Wad file

### ISSUE THREAD

**Issue by nonokirby** [SuperrSonic/WiiMC-SSLC#34]
Is there a wad forwarder for it?

**Comment by SuperrSonic** [comment]
This fork uses the same app directory to work correctly. That means you can use the original forwarder channel.

Additionally, there's a mod of the forwarder that changes the banner colors to the gray theme, and updates the booter to support reading arguments from the meta.xml, however it still reads from /apps/wiimc/boot.dol, it has a different title id, and no splash screen. It's in [the other folder.](https://github.com/SuperrSonic/WiiMC-SSLC/tree/master/other)
