### ISSUE TITLE
onlinemedia.xml is read from apps/wiimc instead of apps/wiimc-ss

### ISSUE THREAD

**Issue by eku** [SuperrSonic/WiiMC-SSLC#36]
Actually, one would expect the file `onlinemedia.xml` to be read from the directory where the DOL is located. It is obviously read from a fixed path `apps/wiimc`. That's bad if you have, like me, both versions of WiiMC installed.

**Comment by SuperrSonic** [comment]
I don't know a clean way to solve this. If you need a solution, just hex edit the boot.dol.
