### ISSUE TITLE
Korean output is not possible.

### ISSUE THREAD

**Issue by DDinghoya** [SuperrSonic/WiiMC-SSLC#39]
Hi SuperrSonic!

For optimization purposes, I continued to use it after support was missing on v2.0.0.

For WiiMC-SS v3.0.0 Revised
. Reworked the language support for the GUI, now only languages that have finished translations are included: English/Spanish/Korean

I was happy with the Korean language support, but if I select Korean, it doesn't print as below attached file;

![No output](https://github.com/SuperrSonic/WiiMC-SSLC/assets/19677686/6a96fcba-f1d2-4055-97c8-47018dee138e)

You're taking a break from WiiMC, but I'll wait for Korean support if I get the chance. :)

Best regards.

**Comment by SuperrSonic** [comment]
I think that for the last big release I experimented a bit with that part of the program and forgot to revert those changes.
It should work now on the 3.0.0 - 2024 release.

**Comment by DDinghoya** [comment]
> I think that for the last big release I experimented a bit with that part of the program and forgot to revert those changes. It should work now on the 3.0.0 - 2024 release.

Checked output Korean and done it!

Thank you! :)
