### ISSUE TITLE
subtitles and USB

### ISSUE THREAD

**Issue by AlfredoDore** [SuperrSonic/WiiMC-SSLC#40]
I don't know which formats work, but I know that VOB and SRT work, wouldn't it be possible to add support for ASS/SSA subtitles?
because ASS/SSA don't work and it wouldn't be interesting to add USB support, on my Wii it's impossible to load USB media

**Comment by SuperrSonic** [comment]
Both are features from the original WiiMC.

The big difference in my fork is that only FAT32 is supported, and that the IOS driver for USB can be changed to the old cIOS one which had better performance over using IOS 58. You can try this alternate module by enabling the meta.xml's "ios=202" argument. https://github.com/SuperrSonic/WiiMC-SSLC/blob/master/other/apps/WiiMC-SS/meta.xml#L27
But you must have the correct cIOS 202 installed. It's always worth trying if your storage device is having issues.

Libass has had many updates in the past. It's possible something broke, but there's simply not enough information to go on.

Does your file work on the original WiiMC? Does it have complex features like karaoke tags?
Did you only try 1 video? SRT and other text-based subtitles are internally converted to the libass format, so you know it is indeed working.

Additionally, you can edit the 'debug' option in the settings.xml file to a value of 4, this will display some info on the OSD bar when playing videos. If m2 (MEM2) is very low, then your video is using up nearly all memory and subtitles might fail.

**Comment by 60fpshacksrock** [comment]
Hmm. The version I am using supports both GC controller and NTFS.

**Comment by AlfredoDore** [comment]
> Both are features from the original WiiMC.
> 
> The big difference in my fork is that only FAT32 is supported, and that the IOS driver for USB can be changed to the old cIOS one which had better performance over using IOS 58. You can try this alternate module by enabling the meta.xml's "ios=202" argument. https://github.com/SuperrSonic/WiiMC-SSLC/blob/master/other/apps/WiiMC-SS/meta.xml#L27 But you must have the correct cIOS 202 installed. It's always worth trying if your storage device is having issues.
> 
> Libass has had many updates in the past. It's possible something broke, but there's simply not enough information to go on.
> 
> Does your file work on the original WiiMC? Does it have complex features like karaoke tags? Did you only try 1 video? SRT and other text-based subtitles are internally converted to the libass format, so you know it is indeed working.
> 
> Additionally, you can edit the 'debug' option in the settings.xml file to a value of 4, this will display some info on the OSD bar when playing videos. If m2 (MEM2) is very low, then your video is using up nearly all memory and subtitles might fail.

In the old version the USB doesn't work either, which I believe is the program, I rip DVDs with MKV make and this program rips without changing the parameters and works perfectly, since I watched things in 480p it's bad on the PC, I started watching it on Wii, which is much better (and my Wii TV is small) anyway, the ASS and SSA subtitles (same format, from aegisub) don't work at all

**Comment by SuperrSonic** [comment]
If your hardware doesn't work with the original WiiMC there's not much I can do. I'm already using up a lot of memory to support two usb modules which exist solely to increase hdd compatibility.

If you can't test with cIOS 202, try ios=56 in the meta.xml, that will turn off usb 2.0 speed but might help your device if it's a power issue.

Assuming your usb works with newer compiled homebrew, upgrading the build libraries could possibly solve your issue, but that's not something I can consider at the moment, since it opens up a whole bunch of new issues.

It would be useful to know how your drive fares in other homebrew apps like nintendont, mplayer ce, wiixplorer, etc.

**Comment by AlfredoDore** [comment]
> If your hardware doesn't work with the original WiiMC there's not much I can do. I'm already using up a lot of memory to support two usb modules which exist solely to increase hdd compatibility.
> 
> If you can't test with cIOS 202, try ios=56 in the meta.xml, that will turn off usb 2.0 speed but might help your device if it's a power issue.
> 
> Assuming your usb works with newer compiled homebrew, upgrading the build libraries could possibly solve your issue, but that's not something I can consider at the moment, since it opens up a whole bunch of new issues.
> 
> It would be useful to know how your drive fares in other homebrew apps like nintendont, mplayer ce, wiixplorer, etc.

I will try

**Comment by AlfredoDore** [comment]
where do I put it?
![image](https://github.com/SuperrSonic/WiiMC-SSLC/assets/90729203/b53dd3d3-4c97-4e81-86f2-0e01987a99d9)

**Comment by SuperrSonic** [comment]
/apps/wiimc/settings.xml

**Comment by SuperrSonic** [comment]
Closing this since it seems like the user resolved their problem.

**Comment by GuckicheLorraine** [comment]
How do you add subs ? Do you need to have srts in a specific place ?
Do you need to embed them in the video ?

**Comment by AlfredoDore** [comment]
> How do you add subs ? Do you need to have srts in a specific place ? Do you need to embed them in the video ?

SRT format, And in the options, there's a way to make it visible.

**Comment by SuperrSonic** [comment]
All subtitles, with the exception of EIA-608 closed captions are internally converted to Advanced SubStation Alpha.
You might as well use them for the extra style information.
