### ISSUE TITLE
GameCube/Wii Disc support?

### ISSUE THREAD

**Issue by 60fpshacksrock** [SuperrSonic/WiiMC-SSLC#41]
Any thoughts on adding support for the Nintendo-DVD FST file system so support for games that have supported media files can be played back on WiiMC?

Since my Wii is one of the newer 'LU' models it doesn't support DVD-R, but WiiMC will not even attempt to allow me to attempt to mount a GC or Wii disc because of this. Can this check be removed if support for official Nintendo discs are added?

**Comment by SuperrSonic** [comment]
At some point I must've thought about that, but my disc drive is broken. Sorry, I can't consider this, but you _can_ mount with WiiXplorer and copy to SD or USB to play in WiiMC.

As for the check, I can remove it. It's known to not be accurate anyway.
