### ISSUE TITLE
YouTube plugin not working

### ISSUE THREAD

**Issue by pollocluck** [SuperrSonic/WiiMC-SSLC#44]
The YouTube (Most popular, search, trending) and Radio Network plugins for the network section of the app don't seem to work anymore. It either says "error loading playlist" or is endlessly loading. This is also the case with the original WiiMC channel. Vimeo and Dailymotion work fine however.

**Comment by SuperrSonic** [comment]
WiiMC has no control over that. You will have to contact the people who run those servers.
