### ISSUE TITLE
HTTPS image links

### ISSUE THREAD

**Issue by Kokokool** [SuperrSonic/WiiMC-SSLC#8]
SS: 
Ok, so im trying to add artwork which works very well. I know that picture size is key to fast pull the image. tvg-logo="" works perfect!

however, HTTPS links to jpg files over the web do not work, while HTTP links to jpg/png files ove the web, works very well. 

This issue does not appear to happen in the other platforms which I share the same playlist with images (movían, ssiptv, etc).

Is there a way to let Wiimc to add accept HTTPs support?

Take Care.

**Comment by SuperrSonic** [comment]
WiiMC specifically ignores links that don't start with http: so try renaming your link and hope for the best.

If this is a request to implement https support, then no I can't do this, I wouldn't even know where to start, even if I did it would be too time consuming. I don't even know why http videos drop out after very little inactivity.
